---
name: Content CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validation:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install raise-mbtools
        run: pip install git+https://github.com/openstax/raise-mbtools@main
      - name: Validate mbz
        run: |
          validate-mbz-html mbz errors.csv mbz --no-style
          CSV_LINES=$(wc -l < errors.csv )
          if [[ $CSV_LINES != "1" ]]; then
            echo "Validation errors found in mbz:"
            cat errors.csv
            exit 1
          fi
      - name: Validate html
        run: |
          validate-mbz-html html errors.csv html
          CSV_LINES=$(wc -l < errors.csv )
          if [[ $CSV_LINES != "1" ]]; then
            echo "Validation errors found in html:"
            cat errors.csv
            exit 1
          fi
      - name: Validate html including tables
        run: |
          validate-mbz-html html errors.csv html --tables
          CSV_LINES=$(wc -l < errors.csv )
          echo "$(($CSV_LINES-1)) table errors found in html"
          cat errors.csv